import { useLocation, useParams } from "react-router-dom";
import { z } from "zod";
import { filesSchema } from "../../schema/TransactionSchema";
import { DocumentTable } from "./document-table";
import { useRef } from "react";
import { useReactToPrint } from "react-to-print";
import { Button } from "@/components/ui/button";
import { useCurrentUserFirstName } from "@/hooks/use-user-hook";
import { filesMutationSchema } from "shared-contract/dist/schema/transactions/mutation-schema";
import { filesQuerySchema } from "shared-contract";

type Props = {
  data: z.infer<typeof filesQuerySchema>[];
};
export const IerPage = ({ data }: Props) => {
  let { state } = useLocation();
  const name = useCurrentUserFirstName();
  const { id } = useParams();
  const componentRef = useRef<HTMLDivElement | null>(null);
  const handlePrint = useReactToPrint({
    content: () => componentRef.current!,
  });
  return (
    <div className="flex flex-col">
      <div className="flex w-full justify-end py-4 ">
        <Button variant="default" className="px-4 py text-white" onClick={handlePrint}>
          Print
        </Button>
      </div>
      <div className="flex flex-col items-center justify-center" ref={componentRef}>
        <DocumentTable data={data} percentage={state ? state.percentage : undefined} />
        <div className="show-print hidden">
          <h1 className="text-muted-foreground text-lg">Generated by:</h1>
          <h1 className="text-lg font-semibold">{name}</h1>
        </div>
      </div>
    </div>
  );
};
